### ISSUE TITLE
Must explicit invoke `should`?

### ISSUE THREAD

**Issue by lazywei** [r7kamura/rspec-request_describer#3]
Hi,

I found that if I'm using

```
it { should == 200 }
```

it will works. But if I'm using

```
it "...." do
  expect(JSON.parse(response.body)["username"]).to eq("lazywei")
end
```

then it will raise error that `response` is `nil`.

I'll need to invoke the `subject` explicitly before using `response`

```
it "...." do
  should == 200
  expect(JSON.parse(response.body)["username"]).to eq("lazywei")
end
```

I don't think this "implicity" is good design. IMHO, I'd prefer I can call `post ...` or something like `do_request` explicitly by myself. This makes the test case more readable.
How do you think?

Thanks.

**Comment by r7kamura** [comment]
This library is for building `subject` from example description that explicitly calls HTTP methods. So, if you don't want to do so, there is no need to use this library.

**Comment by lazywei** [comment]
I like all the good stuff in this library. I'm just wondering if it is possible to add a syntax sugar like
```
def do_request
  subject
end
```
so that I can have testing case like

```
it "should blahblahblah" do
  do_request
  expect(response.status).to eq(200)
  expect(response.body).to other_things
end
```

**Comment by r7kamura** [comment]
I see, it's a nice idea. I added `#send_request` method on v0.0.7 :+1:
https://github.com/r7kamura/rspec-request_describer/compare/v0.0.6...v0.0.7

**Comment by lazywei** [comment]
Thanks for doing this!! :beers:
